In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv(r"C:\Users\AKSHAT\Desktop\Data analyst Projects\Messy Employee Project\Messy_Employee_dataset.csv")
pd.set_option('Display.Max_rows', None)
pd.set_option('Display.Max_columns', None)

df

,Employee_ID,First_Name,Last_Name,Age,Department_Region,Status,Join_Date,Salary,Email,Phone,Performance_Score,Remote_Work
0,EMP1000,Bob,Davis,25.0,DevOps-California,Active,4/2/2021,59767.65,bob.davis@example.com,-1651623197,Average,True
1,EMP1001,Bob,Brown,NaN,Finance-Texas,Active,7/10/2020,65304.66,bob.brown@example.com,-1898471390,Excellent,True
2,EMP1002,Alice,Jones,NaN,Admin-Nevada,Pending,12/7/2023,88145.90,alice.jones@example.com,-5596363211,Good,True
3,EMP1003,Eva,Davis,25.0,Admin-Nevada,Inactive,11/27/2021,69450.99,eva.davis@example.com,-3476490784,Good,True
4,EMP1004,Frank,Williams,25.0,Cloud Tech-Florida,Active,1/5/2022,109324.61,frank.williams@example.com,-1586734256,Poor,False
5,EMP1005,Alice,Garcia,40.0,Sales-Texas,Inactive,6/10/2020,88642.84,alice.garcia@example.com,-5409003485,Good,False
6,EMP1006,Frank,Jones,NaN,Admin-Nevada,Active,4/3/2020,96288.43,frank.jones@example.com,-4518376063,Good,False
7,EMP1007,Bob,Jones,30.0,Cloud Tech-Florida,Inactive,7/17/2022,94497.91,bob.jones@example.com,-4134327559,Average,True
8,EMP1008,Frank,Davis,35.0,Admin-Nevada,Inactive,12/8/2023,115565.82,frank.davis@example.com,-4177656123,Excellent,True
9,EMP1009,Charlie,Johnson,NaN,DevOps-New York,Active,8/4/2022,76561.88,charlie.johnson@example.com,-8156985699,Excellent,True
10,EMP1010,David,Williams,35.0,Cloud Tech-New York,Active,7/6/2024,72081.71,david.williams@example.com,-2720634590,Average,False
11,EMP1011,David,Davis,NaN,DevOps-California,Active,9/4/2023,84946.19,david.davis@example.com,-1238296576,Poor,True
12,EMP1012,Heidi,Williams,30.0,HR-New York,Active,3/5/2024,89295.77,heidi.williams@example.com,-2429543164,Excellent,False
13,EMP1013,Grace,Williams,NaN,Finance-California,Active,10/10/2020,85666.84,grace.williams@example.com,-2669300892,Good,False
14,EMP1014,Alice,Garcia,25.0,Admin-Nevada,Active,6/10/2024,97633.68,alice.garcia@example.com,-1734206968,Excellent,True
15,EMP1015,Grace,Jones,40.0,Sales-Florida,Pending,5/29/2021,117975.49,grace.jones@example.com,-4215291085,Good,True
16,EMP1016,Alice,Brown,25.0,DevOps-Illinois,Inactive,4/23/2024,94867.33,alice.brown@example.com,-7713334475,Poor,False
17,EMP1017,Grace,Garcia,30.0,Finance-Texas,Pending,11/28/2024,100377.65,grace.garcia@example.com,-2639343625,Average,True
18,EMP1018,Charlie,Garcia,NaN,Cloud Tech-Nevada,Inactive,9/19/2024,94726.46,charlie.garcia@example.com,-2044397358,Excellent,False
19,EMP1019,Charlie,Williams,35.0,Admin-Illinois,Pending,1/2/2020,91926.12,charlie.williams@example.com,-7107256365,Average,True
20,EMP1020,Bob,Miller,35.0,HR-New York,Active,5/8/2021,111460.67,bob.miller@example.com,-9411800536,Excellent,True
21,EMP1021,Bob,Jones,40.0,Cloud Tech-Illinois,Active,9/19/2020,96182.56,bob.jones@example.com,-5990048963,Good,False
22,EMP1022,Charlie,Johnson,35.0,Sales-Illinois,Inactive,3/9/2021,115023.94,charlie.johnson@example.com,-6528092427,Average,True
23,EMP1023,David,Garcia,35.0,Finance-Nevada,Pending,2/3/2022,80667.01,david.garcia@example.com,-7572158623,Excellent,False
24,EMP1024,Bob,Brown,30.0,Admin-Texas,Inactive,2/13/2020,91181.61,bob.brown@example.com,-1502745643,Good,True
25,EMP1025,David,Miller,25.0,Cloud Tech-Nevada,Pending,4/30/2020,66025.92,david.miller@example.com,-9485625727,Average,False
26,EMP1026,Frank,Miller,25.0,Sales-New York,Inactive,10/2/2023,83979.01,frank.miller@example.com,-7032032073,Average,False
27,EMP1027,Heidi,Johnson,30.0,Finance-Florida,Active,7/12/2020,56785.16,heidi.johnson@example.com,-2761707586,Excellent,True
28,EMP1028,Grace,Garcia,40.0,Finance-Nevada,Active,10/11/2023,95741.88,grace.garcia@example.com,-7712151341,Excellent,False
29,EMP1029,Alice,Brown,40.0,DevOps-California,Active,5/24/2021,63411.31,alice.brown@example.com,-2849939088,Excellent,True
30,EMP1030,Charlie,Jones,40.0,Admin-California,Inactive,5/26/2021,111214.02,charlie.jones@example.com,-2613715040,Good,True
31,EMP1031,Bob,Smith,25.0,DevOps-Illinois,Active,7/10/2020,114845.69,bob.smith@example.com,-6591520176,Excellent,True
32,EMP1032,Charlie,Brown,40.0,Finance-Florida,Active,11/5/2024,78072.82,charlie.brown@example.com,-7490509758,Average,False
33,EMP1033,Grace,Johnson,25.0,Finance-California,Inactive,8/7/2021,79610.52,grace.johnson@example.com,-2304501895,Average,False
34,EMP1034,Heidi,Miller,30.0,Admin-California,Active,4/29/2020,90542.62,heidi.miller@example.com,-1642361031,Excellent,True
35,EMP1035,Frank,Jones,25.0,Cloud Tech-Illinois,Inactive,10/26/2022,114357.10,frank.jones@example.com,-6642147648,Excellent,True
36,EMP1036,Alice,Brown,NaN,Cloud Tech-New York,Active,5/3/2023,54757.26,alice.brown@example.com,-2515837766,Poor,False
37,EMP1037,Grace,Smith,25.0,Sales-New York,Pending,5/2/2023,52781.92,grace.smith@example.com,-4996165925,Average,True
38,EMP1038,Frank,Smith,35.0,Admin-Nevada,Pending,10/5/2021,66708.02,frank.smith@example.com,-6108573277,Good,True
39,EMP1039,Eva,Williams,40.0,HR-Texas,Active,7/27/2022,93481.15,eva.williams@example.com,-8147617421,Poor,False
40,EMP1040,Bob,Williams,25.0,Sales-New York,Pending,6/27/2021,59271.96,bob.williams@example.com,-4386490809,Excellent,True
41,EMP1041,Bob,Davis,30.0,HR-California,Active,6/16/2022,108362.15,bob.davis@example.com,-8186617944,Excellent,False
42,EMP1042,Alice,Johnson,NaN,HR-Nevada,Active,12/3/2024,59400.38,alice.johnson@example.com,-4918017225,Average,True
43,EMP1043,Bob,Garcia,NaN,Admin-California,Inactive,5/23/2023,64744.08,bob.garcia@example.com,-164597793,Excellent,False
44,EMP1044,Eva,Brown,NaN,Finance-California,Active,7/8/2020,94399.91,eva.brown@example.com,-5232194167,Good,True
45,EMP1045,Alice,Brown,25.0,HR-New York,Pending,6/20/2021,61310.74,alice.brown@example.com,-61027768,Average,True
46,EMP1046,Grace,Garcia,NaN,Cloud Tech-Texas,Active,12/13/2024,98371.37,grace.garcia@example.com,-7499564121,Excellent,False
47,EMP1047,Alice,Davis,35.0,Sales-Illinois,Active,5/30/2022,58921.19,alice.davis@example.com,-310303722,Average,True
48,EMP1048,Alice,Miller,35.0,Admin-Nevada,Active,9/27/2023,57195.55,alice.miller@example.com,-6831472759,Excellent,False
49,EMP1049,Grace,Miller,NaN,DevOps-New York,Active,11/5/2024,61375.12,grace.miller@example.com,-1227770792,Excellent,True
50,EMP1050,Charlie,Davis,40.0,Cloud Tech-New York,Pending,11/11/2021,104767.05,charlie.davis@example.com,-3496050165,Excellent,False
51,EMP1051,David,Miller,35.0,Admin-Nevada,Active,2/22/2022,111051.67,david.miller@example.com,-7998407677,Good,False
52,EMP1052,David,Williams,30.0,Finance-California,Inactive,8/7/2024,105674.18,david.williams@example.com,-9973080694,Good,False
53,EMP1053,Alice,Brown,30.0,Finance-California,Inactive,11/5/2024,54859.45,alice.brown@example.com,-8146717956,Average,False
54,EMP1054,Frank,Davis,NaN,Finance-Nevada,Pending,11/9/2021,115746.60,frank.davis@example.com,-6024375737,Excellent,True
55,EMP1055,Eva,Brown,30.0,Sales-California,Active,8/10/2020,91759.99,eva.brown@example.com,-3959724664,Excellent,True
56,EMP1056,Frank,Garcia,40.0,Sales-Illinois,Active,2/27/2022,112965.33,frank.garcia@example.com,-7293417222,Good,False
57,EMP1057,Alice,Smith,40.0,Cloud Tech-Illinois,Pending,11/7/2023,100360.10,alice.smith@example.com,-2971674337,Excellent,False
58,EMP1058,David,Williams,35.0,Finance-Texas,Pending,11/7/2021,93620.88,david.williams@example.com,-54522800,Good,False
59,EMP1059,Bob,Jones,35.0,Sales-California,Pending,4/16/2022,72832.80,bob.jones@example.com,-5619318373,Excellent,True
60,EMP1060,Charlie,Williams,30.0,Finance-Nevada,Inactive,10/19/2023,102369.42,charlie.williams@example.com,-5508428909,Average,True
61,EMP1061,Eva,Davis,40.0,Sales-Texas,Inactive,8/10/2021,64712.79,eva.davis@example.com,-7711991807,Excellent,True
62,EMP1062,Frank,Jones,40.0,Finance-Florida,Pending,3/13/2021,85782.18,frank.jones@example.com,-1213524786,Excellent,True
63,EMP1063,Charlie,Smith,25.0,HR-Illinois,Pending,7/20/2023,93348.26,charlie.smith@example.com,-1255213759,Poor,False
64,EMP1064,David,Davis,35.0,Admin-New York,Active,2/20/2020,53234.96,david.davis@example.com,-3754821455,Good,False
65,EMP1065,Bob,Johnson,40.0,Finance-Nevada,Pending,2/2/2021,100284.21,bob.johnson@example.com,-5328632665,Excellent,False
66,EMP1066,Grace,Brown,30.0,Admin-Nevada,Pending,1/12/2020,112486.19,grace.brown@example.com,-7850720810,Excellent,True
67,EMP1067,Bob,Smith,40.0,Admin-New York,Pending,11/26/2022,82518.49,bob.smith@example.com,-5562606028,Poor,True
68,EMP1068,Bob,Brown,40.0,Admin-Florida,Pending,12/23/2022,119152.47,bob.brown@example.com,-846684549,Poor,True
69,EMP1069,Heidi,Miller,NaN,DevOps-Illinois,Inactive,8/28/2024,113479.83,heidi.miller@example.com,-4892673898,Good,False
70,EMP1070,Charlie,Johnson,40.0,Finance-California,Active,9/16/2024,94636.30,charlie.johnson@example.com,-7563410855,Poor,False
71,EMP1071,Heidi,Johnson,30.0,HR-Florida,Active,1/1/2024,70000.97,heidi.johnson@example.com,-2884318847,Average,True
72,EMP1072,Frank,Smith,NaN,Cloud Tech-New York,Active,4/18/2021,76812.47,frank.smith@example.com,-5200894345,Poor,False
73,EMP1073,David,Johnson,25.0,Finance-Florida,Inactive,1/16/2023,82614.70,david.johnson@example.com,-8105485100,Average,True
74,EMP1074,Grace,Jones,40.0,Sales-Nevada,Active,10/20/2024,111645.97,grace.jones@example.com,-7490753997,Good,True
75,EMP1075,Heidi,Johnson,25.0,HR-California,Inactive,10/13/2024,112414.91,heidi.johnson@example.com,-9354492682,Good,False
76,EMP1076,David,Brown,40.0,Admin-California,Inactive,9/21/2022,52031.74,david.brown@example.com,-1589357125,Good,True
77,EMP1077,Grace,Brown,30.0,Finance-New York,Pending,12/29/2022,51887.65,grace.brown@example.com,-6110627370,Good,False
78,EMP1078,Alice,Davis,25.0,DevOps-Florida,Active,11/10/2024,82318.89,alice.davis@example.com,-5869886496,Good,True
79,EMP1079,Grace,Brown,35.0,Admin-Florida,Inactive,11/22/2021,103286.08,grace.brown@example.com,-6776228276,Average,False
80,EMP1080,Grace,Davis,35.0,Cloud Tech-Florida,Active,3/14/2024,87759.33,grace.davis@example.com,-2881377027,Average,False
81,EMP1081,Frank,Brown,30.0,DevOps-Texas,Pending,3/23/2020,102796.32,frank.brown@example.com,-5196115939,Good,False
82,EMP1082,David,Jones,25.0,Sales-New York,Active,9/15/2020,83149.27,david.jones@example.com,-8215454469,Poor,True
83,EMP1083,David,Garcia,40.0,DevOps-California,Inactive,12/9/2020,92412.49,david.garcia@example.com,-2296044326,Excellent,True
84,EMP1084,Bob,Davis,30.0,HR-Texas,Pending,2/22/2020,115022.10,bob.davis@example.com,-185106793,Good,False
85,EMP1085,Grace,Williams,40.0,DevOps-New York,Active,4/27/2023,98343.01,grace.williams@example.com,-9756792286,Poor,False
86,EMP1086,Bob,Miller,35.0,DevOps-Illinois,Active,6/18/2024,118869.10,bob.miller@example.com,-7725199662,Excellent,True
87,EMP1087,Frank,Smith,NaN,Finance-Nevada,Inactive,5/21/2020,85417.26,frank.smith@example.com,-6580741208,Good,True
88,EMP1088,Grace,Brown,40.0,Cloud Tech-Florida,Inactive,7/25/2023,112410.25,grace.brown@example.com,-4818139889,Good,True
89,EMP1089,Charlie,Johnson,40.0,Admin-Nevada,Pending,8/25/2023,68905.77,charlie.johnson@example.com,-9837801819,Average,False
90,EMP1090,Heidi,Garcia,40.0,Finance-Nevada,Pending,7/3/2021,72561.32,heidi.garcia@example.com,-4339718955,Excellent,True
91,EMP1091,Bob,Brown,35.0,Finance-New York,Inactive,3/13/2023,92723.22,bob.brown@example.com,-9070562607,Excellent,True
92,EMP1092,Alice,Johnson,40.0,HR-New York,Inactive,3/10/2021,74837.75,alice.johnson@example.com,-5641118241,Poor,False
93,EMP1093,Eva,Miller,NaN,DevOps-California,Pending,1/21/2020,86163.91,eva.miller@example.com,-2412462094,Average,True
94,EMP1094,David,Miller,40.0,Finance-Illinois,Active,11/15/2023,83326.52,david.miller@example.com,-2004615264,Average,True
95,EMP1095,Heidi,Miller,25.0,Cloud Tech-California,Active,4/8/2022,98425.10,heidi.miller@example.com,-4610339936,Average,True
96,EMP1096,Frank,Johnson,40.0,Sales-Illinois,Inactive,5/21/2022,119764.20,frank.johnson@example.com,-8861405785,Average,False
97,EMP1097,Frank,Brown,40.0,HR-California,Inactive,4/17/2021,58445.91,frank.brown@example.com,-1706304890,Excellent,False
98,EMP1098,Bob,Miller,NaN,DevOps-New York,Active,3/19/2021,101702.33,bob.miller@example.com,-3824967182,Excellent,False
99,EMP1099,Eva,Jones,25.0,Admin-California,Active,1/9/2022,NaN,eva.jones@example.com,-2582386869,Good,False
100,EMP1100,Charlie,Davis,35.0,Cloud Tech-Texas,Pending,8/21/2021,98819.22,charlie.davis@example.com,-794200748,Good,False
101,EMP1101,Heidi,Johnson,25.0,Cloud Tech-Illinois,Inactive,8/19/2022,83509.99,heidi.johnson@example.com,-4653984027,Average,False
102,EMP1102,Alice,Johnson,35.0,Finance-Texas,Active,3/31/2022,84422.26,alice.johnson@example.com,-9141612845,Average,False
103,EMP1103,Alice,Brown,30.0,Admin-Illinois,Inactive,6/23/2020,119574.27,alice.brown@example.com,-3985547434,Average,True
104,EMP1104,Grace,Johnson,NaN,Sales-Illinois,Active,5/7/2024,86580.08,grace.johnson@example.com,-5379502096,Good,True
105,EMP1105,Heidi,Johnson,35.0,Sales-Florida,Inactive,3/10/2023,93471.91,heidi.johnson@example.com,-26876810,Poor,False
106,EMP1106,Bob,Miller,30.0,DevOps-New York,Inactive,9/14/2023,55683.12,bob.miller@example.com,-8071569561,Poor,True
107,EMP1107,Bob,Brown,30.0,Cloud Tech-Florida,Inactive,11/12/2023,91566.78,bob.brown@example.com,-175370303,Good,True
108,EMP1108,David,Miller,35.0,DevOps-California,Pending,10/26/2024,81782.19,david.miller@example.com,-5319433749,Good,False
109,EMP1109,Eva,Davis,NaN,DevOps-New York,Inactive,8/23/2020,88119.37,eva.davis@example.com,-4793036148,Good,True
110,EMP1110,Eva,Garcia,30.0,Cloud Tech-Texas,Active,6/11/2024,71532.83,eva.garcia@example.com,-8728399920,Good,True
111,EMP1111,Eva,Davis,40.0,Cloud Tech-Florida,Pending,9/14/2021,98981.36,eva.davis@example.com,-9212493842,Good,True
112,EMP1112,Heidi,Garcia,40.0,Cloud Tech-Illinois,Active,12/26/2024,80242.01,heidi.garcia@example.com,-894870604,Good,True
113,EMP1113,Eva,Miller,25.0,Cloud Tech-New York,Pending,9/8/2024,110236.18,eva.miller@example.com,-6641877579,Average,True
114,EMP1114,Alice,Davis,35.0,Sales-Texas,Active,8/21/2022,86327.47,alice.davis@example.com,-3046875062,Average,False
115,EMP1115,Eva,Brown,30.0,Sales-Florida,Pending,7/25/2024,84420.81,eva.brown@example.com,-5190361331,Average,False
116,EMP1116,Frank,Smith,40.0,HR-California,Pending,8/2/2020,110041.32,frank.smith@example.com,-5411076094,Average,False
117,EMP1117,Heidi,Miller,35.0,DevOps-Florida,Pending,3/16/2020,81837.81,heidi.miller@example.com,-4317350582,Good,True
118,EMP1118,Frank,Garcia,25.0,Finance-Illinois,Active,9/8/2023,110855.72,frank.garcia@example.com,-1997179109,Poor,False
119,EMP1119,Alice,Jones,30.0,Sales-California,Pending,3/29/2024,84894.52,alice.jones@example.com,-651207048,Excellent,True
120,EMP1120,Alice,Garcia,30.0,HR-Illinois,Active,8/12/2021,80668.13,alice.garcia@example.com,-6110804660,Good,True
121,EMP1121,Bob,Jones,25.0,DevOps-Illinois,Active,12/24/2023,61086.47,bob.jones@example.com,-9639907675,Excellent,True
122,EMP1122,Grace,Johnson,25.0,Admin-Texas,Inactive,8/28/2020,95339.68,grace.johnson@example.com,-9915078592,Poor,True
123,EMP1123,Eva,Davis,NaN,DevOps-California,Inactive,9/5/2024,83774.97,eva.davis@example.com,-1109193927,Average,False
124,EMP1124,Heidi,Jones,NaN,Admin-Florida,Active,5/12/2023,85576.86,heidi.jones@example.com,-4567972319,Poor,False
125,EMP1125,Bob,Garcia,35.0,Finance-California,Pending,7/1/2021,107438.46,bob.garcia@example.com,-249685497,Good,True
126,EMP1126,Eva,Johnson,NaN,Sales-Nevada,Inactive,11/7/2024,60401.68,eva.johnson@example.com,-2274954507,Average,False
127,EMP1127,Frank,Smith,35.0,Sales-Illinois,Inactive,7/21/2022,115299.66,frank.smith@example.com,-9203880652,Good,True
128,EMP1128,David,Brown,NaN,Finance-New York,Inactive,3/30/2020,72272.34,david.brown@example.com,-3315377958,Average,False
129,EMP1129,Grace,Brown,40.0,DevOps-Nevada,Active,10/11/2022,117537.71,grace.brown@example.com,-9594652169,Excellent,False
130,EMP1130,Frank,Brown,25.0,Finance-Texas,Pending,7/24/2022,51074.33,frank.brown@example.com,-7303379336,Excellent,True
131,EMP1131,Charlie,Jones,25.0,Finance-California,Inactive,6/30/2023,98489.32,charlie.jones@example.com,-5636205014,Excellent,False
132,EMP1132,Frank,Smith,NaN,Finance-California,Pending,1/11/2024,112120.71,frank.smith@example.com,-812473949,Poor,True
133,EMP1133,Alice,Jones,NaN,Cloud Tech-New York,Pending,11/2/2023,114465.04,alice.jones@example.com,-334234257,Good,False
134,EMP1134,Bob,Davis,40.0,Cloud Tech-Nevada,Pending,11/22/2024,57035.51,bob.davis@example.com,-3230241025,Poor,True
135,EMP1135,Eva,Jones,25.0,Cloud Tech-California,Active,8/23/2021,75092.43,eva.jones@example.com,-1534735527,Excellent,True
136,EMP1136,David,Smith,NaN,Finance-Illinois,Pending,6/11/2024,62603.98,david.smith@example.com,-9611223385,Good,False
137,EMP1137,Grace,Smith,NaN,DevOps-New York,Inactive,4/9/2023,60018.24,grace.smith@example.com,-5596309937,Excellent,False
138,EMP1138,Eva,Davis,40.0,HR-Nevada,Active,7/5/2024,82567.73,eva.davis@example.com,-4253042896,Poor,True
139,EMP1139,Charlie,Smith,25.0,Finance-California,Pending,9/4/2021,94725.71,charlie.smith@example.com,-3179128684,Poor,False
140,EMP1140,Eva,Garcia,40.0,HR-New York,Inactive,10/13/2024,83824.56,eva.garcia@example.com,-7872558776,Poor,False
141,EMP1141,Frank,Smith,NaN,HR-Nevada,Inactive,2/14/2020,118456.11,frank.smith@example.com,-4969033372,Excellent,True
142,EMP1142,Eva,Brown,25.0,Sales-Nevada,Pending,4/10/2020,113743.19,eva.brown@example.com,-6346692547,Good,True
143,EMP1143,Eva,Garcia,30.0,Sales-California,Active,7/27/2023,63309.24,eva.garcia@example.com,-1214785389,Good,False
144,EMP1144,Charlie,Garcia,25.0,DevOps-Nevada,Active,9/24/2021,105202.73,charlie.garcia@example.com,-7895677664,Excellent,True
145,EMP1145,Frank,Davis,30.0,Cloud Tech-California,Inactive,3/10/2024,79085.22,frank.davis@example.com,-7546027340,Good,True
146,EMP1146,Frank,Williams,NaN,Sales-California,Active,6/10/2021,113983.43,frank.williams@example.com,-5148881430,Excellent,True
147,EMP1147,Eva,Williams,35.0,Cloud Tech-Florida,Active,10/15/2020,102790.60,eva.williams@example.com,-1150835353,Good,False
148,EMP1148,Grace,Smith,NaN,HR-Texas,Inactive,1/29/2020,68512.10,grace.smith@example.com,-4439284043,Average,False
149,EMP1149,Frank,Garcia,35.0,Sales-Florida,Pending,1/30/2022,57584.23,frank.garcia@example.com,-5669078262,Average,True
150,EMP1150,Alice,Williams,NaN,Sales-California,Pending,3/29/2021,95335.67,alice.williams@example.com,-3373898774,Poor,False
151,EMP1151,Heidi,Williams,35.0,DevOps-Florida,Active,10/13/2020,53174.28,heidi.williams@example.com,-1536637779,Average,True
152,EMP1152,Heidi,Smith,25.0,Cloud Tech-New York,Pending,10/4/2020,77205.21,heidi.smith@example.com,-5292407552,Average,False
153,EMP1153,Grace,Williams,NaN,DevOps-Nevada,Active,12/18/2024,79041.92,grace.williams@example.com,-6668459089,Average,True
154,EMP1154,Heidi,Jones,NaN,Finance-California,Active,11/14/2023,75937.10,heidi.jones@example.com,-2259999662,Excellent,True
155,EMP1155,David,Johnson,35.0,Cloud Tech-Nevada,Inactive,1/20/2023,113118.73,david.johnson@example.com,-6186371596,Average,False
156,EMP1156,Alice,Davis,40.0,HR-New York,Active,10/2/2024,107693.38,alice.davis@example.com,-4121820969,Average,True
157,EMP1157,David,Johnson,NaN,Cloud Tech-Texas,Inactive,5/13/2021,119217.46,david.johnson@example.com,-2316433480,Poor,False
158,EMP1158,David,Smith,25.0,Sales-New York,Pending,3/18/2021,106913.71,david.smith@example.com,-7058025661,Average,False
159,EMP1159,Charlie,Brown,NaN,Cloud Tech-California,Active,9/23/2020,87815.08,charlie.brown@example.com,-1286716322,Average,True
160,EMP1160,Bob,Davis,25.0,Admin-Texas,Inactive,6/5/2024,105190.21,bob.davis@example.com,-4672994937,Good,True
161,EMP1161,Alice,Smith,30.0,HR-Texas,Active,2/28/2024,79467.24,alice.smith@example.com,-7430271692,Poor,False
162,EMP1162,Bob,Garcia,40.0,Finance-California,Pending,4/30/2023,57633.78,bob.garcia@example.com,-8597779013,Poor,True
163,EMP1163,Alice,Brown,NaN,HR-Florida,Pending,3/4/2020,54257.78,alice.brown@example.com,-7546926328,Poor,True
164,EMP1164,Grace,Johnson,40.0,DevOps-Texas,Inactive,12/29/2023,113679.06,grace.johnson@example.com,-6762916031,Poor,True

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Employee_ID        1020 non-null   object
 1   First_Name         1020 non-null   object
 2   Last_Name          1020 non-null   object
 3   Age                809 non-null    float64
 4   Department_Region  1020 non-null   object
 5   Status             1020 non-null   object
 6   Join_Date          1020 non-null   object
 7   Salary             996 non-null    float64
 8   Email              1020 non-null   object
 9   Phone              1020 non-null   int64
 10  Performance_Score  1020 non-null   object
 11  Remote_Work        1020 non-null   bool
dtypes: bool(1), float64(2), int64(1), object(8)
memory usage: 88.8+ KB

In [5]:
df.head()

,Employee_ID,First_Name,Last_Name,Age,Department_Region,Status,Join_Date,Salary,Email,Phone,Performance_Score,Remote_Work
0,EMP1000,Bob,Davis,25.0,DevOps-California,Active,4/2/2021,59767.65,bob.davis@example.com,-1651623197,Average,True
1,EMP1001,Bob,Brown,NaN,Finance-Texas,Active,7/10/2020,65304.66,bob.brown@example.com,-1898471390,Excellent,True
2,EMP1002,Alice,Jones,NaN,Admin-Nevada,Pending,12/7/2023,88145.90,alice.jones@example.com,-5596363211,Good,True
3,EMP1003,Eva,Davis,25.0,Admin-Nevada,Inactive,11/27/2021,69450.99,eva.davis@example.com,-3476490784,Good,True
4,EMP1004,Frank,Williams,25.0,Cloud Tech-Florida,Active,1/5/2022,109324.61,frank.williams@example.com,-1586734256,Poor,False

In [6]:
df.tail()

,Employee_ID,First_Name,Last_Name,Age,Department_Region,Status,Join_Date,Salary,Email,Phone,Performance_Score,Remote_Work
1015,EMP2015,David,Miller,30.0,HR-California,Active,8/19/2023,NaN,david.miller@example.com,-3546212759,Good,True
1016,EMP2016,David,Johnson,30.0,Cloud Tech-Texas,Inactive,11/7/2021,100215.06,david.johnson@example.com,-2508261122,Good,True
1017,EMP2017,Charlie,Williams,40.0,Finance-New York,Active,10/4/2023,114587.11,charlie.williams@example.com,-1261632487,Average,False
1018,EMP2018,Alice,Garcia,30.0,HR-Florida,Inactive,12/16/2024,71318.79,alice.garcia@example.com,-8995729892,Good,True
1019,EMP2019,Heidi,Jones,30.0,DevOps-Illinois,Pending,2/22/2021,77764.24,heidi.jones@example.com,-7629745492,Average,False

In [7]:
df.nunique()

Employee_ID          1020
First_Name              8
Last_Name               8
Age                     4
Department_Region      36
Status                  3
Join_Date             760
Salary                978
Email                  64
Phone                1020
Performance_Score       4
Remote_Work             2
dtype: int64

In [14]:
df.duplicated().sum()

np.int64(0)

In [17]:
df["First_Name"].nunique()

8